		<!-- ======================================================================================== -->
		<!-- Alexandria IS DISTRIBUTED "AS IS". NO WARRANTY OF ANY KIND IS EXPRESSED OR IMPLIED.      -->
		<!-- YOU USE AT YOUR OWN RISK. THE AUTHOR WILL NOT BE LIABLE FOR DATA LOSS, DAMAGES, LOSS OF  -->
		<!-- PROFITS OR ANY OTHER KIND OF LOSS WHILE USING OR MISUSING THIS SOFTWARE.                 -->
		<!-- ======================================================================================== -->
		<!-- **************************************************************************************** -->
		<!-- Alert Alexandria (optional)                                                              -->
		<!-- Indicates that Alexandria is available on this page                                      -->
		<!-- **************************************************************************************** -->
		<script type="text/javascript" language="JavaScript1.2" src="scripts/scriptsalexandria/alert.fr.js"></script>
		<!-- **************************************************************************************** -->
		<!-- Alexandria's parameters for Webmasters                                                   -->
		<!-- Download and place on your site the "alexandria.wm.js" to update your special terms.     -->
		<!-- Customization is only possible for registered customers.                                 -->
		<!-- **************************************************************************************** -->
		<script type="text/javascript" language="JavaScript1.2" src="scripts/scriptsalexandria/alexandria.wm.js"></script>
		<!-- **************************************************************************************** -->
		<!-- Alexandria's engine                                                                      -->
		<!-- Copy the lines below in each page you want Alexandria's functionalities to be available. -->
		<!-- **************************************************************************************** -->
		<script type="text/javascript" language="JavaScript1.2" src="scripts/scriptsalexandria/alexandria.main.js"></script>
		<!-- ======================================================================================== -->
		<link rel="StyleSheet" href="http://www.sensagent.com/alexandria/css/alexandria.window.css" type="text/css">