<?php
	if ($niveau==1) {
			echo '<option value="1" selected>'.new_versionlinguistique("text8");
			} else {
			echo '<option value="1">'.new_versionlinguistique("text8");
			}
	if ($niveau==5) {
			echo '<option value="5" selected>'.new_versionlinguistique("text63");
			} else {
			echo '<option value="5">'.new_versionlinguistique("text63");
			}
	if ($niveau==10) {
			echo '<option value="10" selected>'.new_versionlinguistique("text64");
			} else {
			echo '<option value="10">'.new_versionlinguistique("text64");
			}
?>