<?php
	if ($niveau==1) {
			echo '<option value="1" selected>'.versionlinguistique(8);
			} else {
			echo '<option value="1">'.versionlinguistique(8);
			}
	if ($niveau==5) {
			echo '<option value="5" selected>'.versionlinguistique(63);
			} else {
			echo '<option value="5">'.versionlinguistique(63);
			}
	if ($niveau==10) {
			echo '<option value="10" selected>'.versionlinguistique(64);
			} else {
			echo '<option value="10">'.versionlinguistique(64);
			}
?>