					<table border="0" cellpadding="0" cellspacing="2" width="900">
						<tr>
							<td><a href="http://www.msh-lorraine.fr/actualites/" target="_blank"><img width="200" src="visuel/logos/Logo_MSH.jpg" border="0"></a></td>
							<td><a href="http://www.atilf.fr/" target="_blank"><img width="200" src="visuel/logos/Logo_ATILF_new.png" border="0"></a></td>
							<td><a href="http://www.univ-lorraine.fr/" target="_blank"><img width="190" src="visuel/logos/univ_lorraine.jpg" border="0"></a></td>
							<td><a href="http://www.cnrs.fr/" target="_blank"><img width="80" src="visuel/logos/CNRS.png" border="0"></a></td>
						</tr>
					</table>