					<table border="0" cellpadding="0" cellspacing="0" width="900">
						<tr>
							<td align="center" valign="middle"><a href="index.php?lg=<?php echo $lg; ?>"><span class="texte_menu"><?php echo versionlinguistique(1) //Accueil ?></span></a></td>
							<td align="center" valign="middle"><a href="conseils.php?lg=<?php echo $lg; ?>"><span class="texte_menu"><?php echo versionlinguistique(2)// Conseils ?></span></a></td>
							<td align="center" valign="middle"><a href="ressources.htm?lg=<?php echo $lg; ?>"><span class="texte_menu"><?php echo versionlinguistique(3)// Ressources multimedia ?></span></a></td>
							<td align="center" valign="middle"><a href="liens.htm?lg=<?php echo $lg; ?>"><span class="texte_menu"><?php echo versionlinguistique(5)// Liens utiles ?></span></a></td>
							<td align="center" valign="middle"><a href="profil.php?lg=<?php echo $lg; ?>"><span class="texte_menu"><?php echo versionlinguistique(15)// Profil ?></span></a></td>
							<td align="center" valign="middle"><a href="contact.htm?lg=<?php echo $lg; ?>"><span class="texte_menu"><?php echo versionlinguistique(4)// Contact ?></span></a></td>
							<td align="center" valign="middle"><a href="deconnexion.php?lg=<?php echo $lg; ?>"><span class="texte_menu"><?php echo versionlinguistique(17)// déconnexion ?></span></a></td>
						</tr>
					</table>